storage_account: etlstorageproject

paths:
  raw: /mnt/data/raw/
  bronze: /mnt/data/bronze/
  silver: /mnt/data/silver/
  gold: /mnt/data/gold/

files:
  input_file: customers01.csv

columns:
  drop_columns: ["temp_col"]

business:
  aggregation_column: department
  
