storage_account: etlstorageproject

paths:
  raw: /mnt/raw/
  bronze: /mnt/bronze/raw/
  silver: /mnt/silver/clean/
  gold: /mnt/gold/

files:
  input_files: ["customers01.csv","sales01.csv","products01.csv"]
  
file_format: parquet
  
