storage_account: etlstorageproject
paths:
  raw: "/Workspace/Repos/dynamodebanjanuchiha@gmail.com/etl-medallion-project/data/raw/"
  bronze: "/Workspace/Repos/dynamodebanjanuchiha@gmail.com/etl-medallion-project/data/bronze/"
  silver: "/Workspace/Repos/dynamodebanjanuchiha@gmail.com/etl-medallion-project/data/silver/"
  gold: "/Workspace/Repos/dynamodebanjanuchiha@gmail.com/etl-medallion-project/data/gold/"

files:
  input_file: customers.csv

columns:
  drop_columns: ["temp_col"]

business:
  aggregation_column: department
  
